using '../infra/network/main.bicep'

param location = '__REQUIRED_LOCATION__'
param virtualNetworkName = '__REQUIRED_VNET_NAME__'
param virtualNetworkAddressPrefix = '__REQUIRED_VNET_CIDR__'
param agentSubnetPrefix = '__REQUIRED_AGENT_SUBNET_CIDR__'
param privateEndpointSubnetPrefix = '__REQUIRED_PRIVATE_ENDPOINT_SUBNET_CIDR__'
param firewallPrivateIp = '__REQUIRED_FIREWALL_PRIVATE_IP__'
param foundryResourceId = '__REQUIRED_FOUNDRY_RESOURCE_ID__'
param storageResourceId = '__REQUIRED_STORAGE_RESOURCE_ID__'
param searchResourceId = '__REQUIRED_SEARCH_RESOURCE_ID__'
param cosmosResourceId = '__REQUIRED_COSMOS_RESOURCE_ID__'
param keyVaultResourceId = '__REQUIRED_KEY_VAULT_RESOURCE_ID__'
param expiryDate = '__REQUIRED_EXPIRY_DATE__'
