AdvisorResources
| where type =~ "microsoft.advisor/recommendations"
| extend
    recommendationSubCategory = tostring(properties.extendedProperties.recommendationSubCategory),
    recommendationState = tostring(properties.platformState),
    tracked = tostring(properties.tracked),
    resourceId = tolower(tostring(properties.resourceMetadata.resourceId)),
    impact = tostring(properties.impact),
    problem = tostring(properties.shortDescription.problem),
    solution = tostring(properties.shortDescription.solution),
    recommendationTypeId = tostring(properties.recommendationTypeId)
| where recommendationSubCategory == "ServiceUpgradeAndRetirement"
| where recommendationState == "New" and isempty(tracked)
| project resourceId, recommendationTypeId, impact, problem, solution, subscriptionId
| order by impact asc, resourceId asc
