using './main.bicep'

param location = '__REQUIRED_DEPLOYMENT_LOCATION__'
param applicationInsightsResourceId = '__REQUIRED_APPLICATION_INSIGHTS_RESOURCE_ID__'
param actionGroupResourceId = '__REQUIRED_ACTION_GROUP_RESOURCE_ID__'
param workbookDisplayName = '__REQUIRED_WORKBOOK_DISPLAY_NAME__'
param serviceName = '__REQUIRED_SERVICE_NAME__'
param environment = 'nonproduction'
param requestErrorRateThreshold = '__REQUIRED_REQUEST_ERROR_RATE_PERCENT__'
param toolFailureThreshold = '__REQUIRED_TOOL_FAILURE_COUNT__'
param qualityFailureThreshold = '__REQUIRED_QUALITY_FAILURE_COUNT__'
